---
- hosts: rancher-node
  gather_facts: false
  pre_tasks:
    - name: Install Python
      raw: bash -c "test -e /usr/bin/python || (yum -y update && yum install -y python) || (apt -y update && apt install -y python-minimal) || (apt -y update && apt install -y python2-minimal)"
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0
      changed_when: result.stdout != ""

    - action: setup

  roles:
    - common
