# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.ssh.insert_key = false

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common jq unzip -y
    echo "deb http://pkg.camptocamp.net/apt xenial/staging sysadmin docker" | sudo tee -a /etc/apt/sources.list
    wget -O- "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x25167F35256F82B2CA594A3DF4831166EFDCBABE" | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install docker-ce -y
    sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo usermod -aG docker vagrant

    # Add default vagrant key
    curl -k https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub > /home/vagrant/.ssh/authorized_keys
    chmod 0700 /home/vagrant/.ssh
    chmod 0600 /home/vagrant/.ssh/authorized_keys
    cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys

  SHELL


  config.vm.provision "shell", path: "install.sh"
  config.vm.provision "shell", path: "prepare.sh"
end
