- name: Check if Docker already installed
  shell: command -v docker >/dev/null 2>&1
  register: is_docker_installed
  ignore_errors: yes
  changed_when: false

- name: Install Docker-io
  apt:
    name: docker.io
    state: latest
  when: ansible_facts['os_family'] == "Debian" and is_docker_installed.rc != 0

- name: Enable Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Configure Docker daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker

- meta: flush_handlers
