- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"

- import_tasks: docker.yaml
- import_tasks: rancher.yaml
